### ISSUE TITLE
替换失败不知道啥原因

### ISSUE THREAD

**Issue by wtx2017** [flywithrain/easyword#1]
![image](https://user-images.githubusercontent.com/26156424/147210711-24fcfac7-2827-4ff3-9271-408891e2bc97.png)
![image](https://user-images.githubusercontent.com/26156424/147210819-31604364-a108-40a7-9dbd-8b60c4353a72.png)
![image](https://user-images.githubusercontent.com/26156424/147210852-aa2779c3-c016-4f49-af4d-85c8f0f8d872.png)
列表与前面的替换都成功了，就后面这个替换有问题,麻烦帮忙看一下

**Comment by flywithrain** [comment]
应该是2.0版本吧，老问题了，前两天有人提我刚更新代码，我上传2.0.1版本你换下

**Comment by wtx2017** [comment]
谢谢
